version: "3"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
  api:
    image: registry-intl.cn-hangzhou.aliyuncs.com/vue-online-shop-zzj/api
    restart: always
  nginx:
    image: registry-intl.cn-hangzhou.aliyuncs.com/vue-online-shop-zzj/nginx
    restart: always
    ports:
      - 8080:80
